<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-JNDOI91" failures="1" tests="3" name="Verify" time="18.334" errors="0" timestamp="2024-09-26T00:09:57 IST">
  <testcase classname="Tests.NewTest" name="verifyLogin" time="0.042">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [data:,]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [data:,]
at Tests.NewTest.verifyLogin(NewTest.java:60)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase classname="Tests.NewTest" name="LaunchUrl" time="3.951"/>
  <testcase classname="Tests.NewTest" name="Login" time="15.352"/>
</testsuite> <!-- Verify -->
